services:

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  task:
    build: /.
    hostname: task
    depends_on:
      - db
    environment:
      TASK_HOST: task
      TASK_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - '8080:8080'
