server:
  address: ${TASK_HOST:127.0.0.1}
  port: ${TASK_PORT:8080}
spring:
  application:
    name: task
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/tasks
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update
  liquibase.change-log: classpath:db/liquibase-changelog.xml
token.signing.key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
logging.level.org.springframework.security: DEBUG